"""
AI Optimization Analysis Engine

Analyzes content to produce a comprehensive AI Visibility Score and
detailed recommendations for improving LLM discoverability.
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass, field

from app.services.llm_client import llm_client


# ─── Score dataclass ─────────────────────────────────────────────────────────

@dataclass
class AIVisibilityScore:
    overall: float = 0.0

    entity_clarity: float = 0.0
    category_ownership: float = 0.0
    educational_authority: float = 0.0
    prompt_coverage: float = 0.0
    comparison_coverage: float = 0.0
    ecosystem_coverage: float = 0.0
    external_authority: float = 0.0
    community_signal: float = 0.0
    consistency: float = 0.0
    structure_quality: float = 0.0

    # Weighted contributions (must sum to 1.0)
    WEIGHTS: dict = field(default_factory=lambda: {
        "entity_clarity": 0.15,
        "category_ownership": 0.12,
        "educational_authority": 0.12,
        "prompt_coverage": 0.15,
        "comparison_coverage": 0.10,
        "ecosystem_coverage": 0.10,
        "external_authority": 0.10,
        "community_signal": 0.06,
        "consistency": 0.05,
        "structure_quality": 0.05,
    })

    def calculate_overall(self) -> float:
        scores = {
            "entity_clarity": self.entity_clarity,
            "category_ownership": self.category_ownership,
            "educational_authority": self.educational_authority,
            "prompt_coverage": self.prompt_coverage,
            "comparison_coverage": self.comparison_coverage,
            "ecosystem_coverage": self.ecosystem_coverage,
            "external_authority": self.external_authority,
            "community_signal": self.community_signal,
            "consistency": self.consistency,
            "structure_quality": self.structure_quality,
        }
        self.overall = sum(
            scores[k] * self.WEIGHTS[k] for k in self.WEIGHTS
        )
        return round(self.overall, 1)

    def to_dict(self) -> dict:
        return {
            "overall": round(self.overall, 1),
            "entity_clarity": round(self.entity_clarity, 1),
            "category_ownership": round(self.category_ownership, 1),
            "educational_authority": round(self.educational_authority, 1),
            "prompt_coverage": round(self.prompt_coverage, 1),
            "comparison_coverage": round(self.comparison_coverage, 1),
            "ecosystem_coverage": round(self.ecosystem_coverage, 1),
            "external_authority": round(self.external_authority, 1),
            "community_signal": round(self.community_signal, 1),
            "consistency": round(self.consistency, 1),
            "structure_quality": round(self.structure_quality, 1),
        }


# ─── Analysis Engine ─────────────────────────────────────────────────────────

class AnalysisEngine:
    """
    Analyzes content corpus to determine AI Visibility Score.
    Each signal is evaluated by a specialized prompt sent to Claude.
    """

    SYSTEM_PROMPT = """You are an expert AI Engine Optimization (AEO) analyst.
Your job is to evaluate content and determine how likely it is to appear
in answers generated by Large Language Models like ChatGPT, Claude, Gemini,
and Grok. You analyze content signals that LLMs use when deciding which
products or companies to mention. Be precise, critical, and specific.
Always respond with valid JSON as instructed."""

    async def analyze(
        self,
        product_name: str,
        product_description: str,
        product_category: str,
        content_corpus: list[dict],  # list of {title, text, url?}
        competitors: list[str] | None = None,
    ) -> dict:
        """
        Run full AEO analysis pipeline.
        Returns complete analysis report dict.
        """
        # Prepare content sample (limit tokens)
        corpus_sample = self._prepare_corpus_sample(content_corpus, max_chars=40_000)

        # Run all signal analyses in parallel
        (
            entity_result,
            category_result,
            educational_result,
            prompt_result,
            comparison_result,
            ecosystem_result,
            structure_result,
            consistency_result,
        ) = await asyncio.gather(
            self._analyze_entity_clarity(product_name, product_description, corpus_sample),
            self._analyze_category_ownership(product_name, product_category, corpus_sample),
            self._analyze_educational_authority(product_name, product_category, corpus_sample),
            self._analyze_prompt_coverage(product_name, product_category, corpus_sample),
            self._analyze_comparison_coverage(product_name, competitors or [], corpus_sample),
            self._analyze_ecosystem_coverage(product_name, product_category, corpus_sample),
            self._analyze_structure_quality(corpus_sample),
            self._analyze_consistency(product_name, product_description, corpus_sample),
        )

        # Build score object
        score = AIVisibilityScore(
            entity_clarity=entity_result.get("score", 0),
            category_ownership=category_result.get("score", 0),
            educational_authority=educational_result.get("score", 0),
            prompt_coverage=prompt_result.get("score", 0),
            comparison_coverage=comparison_result.get("score", 0),
            ecosystem_coverage=ecosystem_result.get("score", 0),
            structure_quality=structure_result.get("score", 0),
            consistency=consistency_result.get("score", 0),
            # External authority and community signals require external data
            external_authority=0.0,
            community_signal=0.0,
        )
        score.calculate_overall()

        # Build recommendations
        all_recommendations = []
        for result in [
            entity_result, category_result, educational_result, prompt_result,
            comparison_result, ecosystem_result, structure_result, consistency_result,
        ]:
            all_recommendations.extend(result.get("recommendations", []))

        # Prioritize recommendations by impact
        all_recommendations.sort(key=lambda r: r.get("impact", 0), reverse=True)

        # Generate content roadmap
        content_roadmap = await self._generate_content_roadmap(
            product_name=product_name,
            product_category=product_category,
            score=score,
            prompt_clusters=prompt_result.get("prompt_clusters", {}),
            content_gaps=ecosystem_result.get("content_gaps", []),
        )

        return {
            "scores": score.to_dict(),
            "findings": {
                "entity_clarity": entity_result,
                "category_ownership": category_result,
                "educational_authority": educational_result,
                "prompt_coverage": prompt_result,
                "comparison_coverage": comparison_result,
                "ecosystem_coverage": ecosystem_result,
                "structure_quality": structure_result,
                "consistency": consistency_result,
            },
            "recommendations": all_recommendations[:20],  # Top 20
            "content_gaps": ecosystem_result.get("content_gaps", []),
            "prompt_clusters": prompt_result.get("prompt_clusters", {}),
            "content_roadmap": content_roadmap,
        }

    # ─── Signal analyzers ─────────────────────────────────────────────────────

    async def _analyze_entity_clarity(
        self, product_name: str, product_description: str, corpus: str
    ) -> dict:
        prompt = f"""Analyze how clearly the content establishes what {product_name} is as an entity.

PRODUCT: {product_name}
DESCRIPTION: {product_description}

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Does the content explicitly state what {product_name} is? (e.g., "{product_name} is a [category] platform for [use case]")
2. Is the entity definition repeated consistently?
3. Is the product name clearly associated with its category?
4. Are key attributes (features, target users, value proposition) stated clearly?
5. Would an LLM reading this content understand exactly what {product_name} does?

Respond with this JSON structure:
{{
  "score": <0-100>,
  "entity_defined": <true/false>,
  "definition_examples": ["<quote from content>"],
  "issues": ["<specific issue found>"],
  "recommendations": [
    {{"action": "<specific action>", "impact": <1-10>, "example": "<example content to add>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_category_ownership(
        self, product_name: str, category: str, corpus: str
    ) -> dict:
        prompt = f"""Analyze how strongly {product_name} positions itself as a leader in "{category}".

PRODUCT: {product_name}
CATEGORY: {category}

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Is the category "{category}" mentioned consistently across content?
2. Does the content use category-defining language?
3. Does content explain the category itself (not just the product)?
4. Is {product_name} positioned as authoritative within the category?
5. Does content define problems the category solves?

Respond with:
{{
  "score": <0-100>,
  "category_mentions": <count>,
  "category_authority_signals": ["<signal found>"],
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_educational_authority(
        self, product_name: str, category: str, corpus: str
    ) -> dict:
        prompt = f"""Analyze the educational authority of {product_name}'s content in the "{category}" space.

PRODUCT: {product_name}
CATEGORY: {category}

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Does content explain key concepts and terminology in the category?
2. Are educational articles present (e.g., "What is {category}?")?
3. Does content provide original insights or frameworks?
4. Are there how-to guides, tutorials, or best practices?
5. Does the depth of content signal expertise?
6. Would LLMs cite this content as authoritative?

Respond with:
{{
  "score": <0-100>,
  "educational_content_found": ["<title or description>"],
  "missing_educational_content": ["<type of content missing>"],
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example article title>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_prompt_coverage(
        self, product_name: str, category: str, corpus: str
    ) -> dict:
        prompt = f"""Analyze how well {product_name}'s content aligns with natural user prompts asked to AI systems.

PRODUCT: {product_name}
CATEGORY: {category}

CONTENT SAMPLE:
{corpus[:8000]}

Generate the top 20 prompts users actually ask AI assistants about {category} and {product_name}.
Then evaluate how well the content covers each prompt.

Respond with:
{{
  "score": <0-100>,
  "prompt_clusters": {{
    "what_is": ["What is {category}?", "What does {product_name} do?"],
    "best_tools": ["Best {category} tools", "Top {category} platforms"],
    "how_to": ["How to {category}", "How to use {product_name}"],
    "comparisons": ["{product_name} vs alternatives", "Compare {category} tools"],
    "use_cases": ["When to use {category}", "{category} for enterprise"]
  }},
  "covered_prompts": ["<prompt covered by existing content>"],
  "missing_prompts": ["<prompt not covered>"],
  "coverage_percentage": <0-100>,
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_comparison_coverage(
        self, product_name: str, competitors: list[str], corpus: str
    ) -> dict:
        competitors_str = ", ".join(competitors) if competitors else "major alternatives"
        prompt = f"""Analyze the comparison and competitive positioning content for {product_name}.

PRODUCT: {product_name}
KNOWN COMPETITORS: {competitors_str}

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Does content include comparison articles (e.g., "{product_name} vs [Competitor]")?
2. Are there "best tools" or "top alternatives" articles?
3. Does content objectively compare features?
4. Is there content explaining when to choose {product_name} vs alternatives?
5. Does content appear in comparison contexts that LLMs might cite?

Respond with:
{{
  "score": <0-100>,
  "comparisons_found": ["<comparison article or section found>"],
  "missing_comparisons": ["<comparison that should exist>"],
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example article title>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_ecosystem_coverage(
        self, product_name: str, category: str, corpus: str
    ) -> dict:
        prompt = f"""Map the complete topic ecosystem around {product_name} in the "{category}" space,
then evaluate content coverage.

PRODUCT: {product_name}
CATEGORY: {category}

CONTENT SAMPLE:
{corpus[:8000]}

Identify ALL topics that belong to the {category} ecosystem.
Then determine which are covered, which are gaps.

Respond with:
{{
  "score": <0-100>,
  "ecosystem_topics": [
    {{"topic": "<topic>", "importance": <1-10>, "covered": <true/false>}}
  ],
  "content_gaps": [
    {{"topic": "<missing topic>", "importance": <1-10>, "suggested_title": "<article title>", "suggested_format": "blog|faq|guide|comparison"}}
  ],
  "covered_count": <number>,
  "total_count": <number>,
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_structure_quality(self, corpus: str) -> dict:
        prompt = f"""Analyze the structural quality of this content from an AEO perspective.
LLMs prefer content that is well-structured, clearly defined, and easy to parse.

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Are headings (H1, H2, H3) used effectively?
2. Are definitions clearly stated?
3. Are examples provided?
4. Are FAQs present?
5. Is content scannable (lists, tables, short paragraphs)?
6. Is structured data markup suggested?

Respond with:
{{
  "score": <0-100>,
  "structure_signals": {{
    "has_headings": <true/false>,
    "has_definitions": <true/false>,
    "has_examples": <true/false>,
    "has_faqs": <true/false>,
    "has_lists": <true/false>,
    "has_tables": <true/false>
  }},
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    async def _analyze_consistency(
        self, product_name: str, product_description: str, corpus: str
    ) -> dict:
        prompt = f"""Analyze the consistency of how {product_name} is described across its content.

PRODUCT: {product_name}
CANONICAL DESCRIPTION: {product_description}

CONTENT SAMPLE:
{corpus[:8000]}

Evaluate:
1. Is the product described consistently across different content pieces?
2. Do different pages use conflicting category positioning?
3. Are value propositions consistent?
4. Are there contradictions in feature descriptions?

Respond with:
{{
  "score": <0-100>,
  "consistency_issues": ["<specific inconsistency found>"],
  "consistent_signals": ["<signal that is consistent>"],
  "issues": ["<issue>"],
  "recommendations": [
    {{"action": "<action>", "impact": <1-10>, "example": "<example>"}}
  ]
}}"""

        return await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)

    # ─── Content roadmap ──────────────────────────────────────────────────────

    async def _generate_content_roadmap(
        self,
        product_name: str,
        product_category: str,
        score: AIVisibilityScore,
        prompt_clusters: dict,
        content_gaps: list,
    ) -> list[dict]:
        gaps_str = "\n".join(
            f"- {g.get('topic', '')}: importance {g.get('importance', 0)}/10"
            for g in content_gaps[:15]
        )
        prompt_str = "\n".join(
            f"- {cluster}: {', '.join(prompts[:3])}"
            for cluster, prompts in prompt_clusters.items()
        )

        prompt = f"""Create a prioritized content roadmap for {product_name} to improve AI Engine Optimization.

CURRENT SCORES:
- Overall: {score.overall}/100
- Entity Clarity: {score.entity_clarity}/100
- Educational Authority: {score.educational_authority}/100
- Prompt Coverage: {score.prompt_coverage}/100
- Comparison Coverage: {score.comparison_coverage}/100

CONTENT GAPS:
{gaps_str}

PROMPT CLUSTERS TO COVER:
{prompt_str}

Generate a prioritized 90-day content roadmap (max 20 items).

Respond with:
{{
  "roadmap": [
    {{
      "priority": <1-20>,
      "title": "<article or content title>",
      "type": "blog|guide|faq|comparison|landing_page|documentation",
      "target_prompts": ["<prompt this content answers>"],
      "expected_impact": "<description of expected AEO improvement>",
      "score_impact": {{"metric": "<score name>", "estimated_gain": <0-20>}},
      "outline": ["<H2 section>"]
    }}
  ]
}}"""

        result = await llm_client.extract_json(prompt, system=self.SYSTEM_PROMPT)
        return result.get("roadmap", [])

    # ─── Helpers ──────────────────────────────────────────────────────────────

    def _prepare_corpus_sample(
        self, content_corpus: list[dict], max_chars: int = 40_000
    ) -> str:
        parts = []
        total = 0
        for item in content_corpus:
            title = item.get("title", "Untitled")
            text = item.get("text", "")
            url = item.get("url", "")
            header = f"\n\n{'='*60}\nCONTENT: {title}"
            if url:
                header += f"\nURL: {url}"
            header += f"\n{'='*60}\n"
            chunk = header + text[:2000]
            if total + len(chunk) > max_chars:
                break
            parts.append(chunk)
            total += len(chunk)
        return "\n".join(parts)


# ─── Singleton ────────────────────────────────────────────────────────────────

analysis_engine = AnalysisEngine()
