// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvbsskmzydeazdidspgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2YnNza216eWRlYXpkaWRzcGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMzc3NjYsImV4cCI6MjA4ODYxMzc2Nn0.GLoL7JiTHEUwbrHaSEUQMDRO7IAq-dhsimVqog26nuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});